language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_cbd4cd1910df_key -iv $encrypted_cbd4cd1910df_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- pip install ansible==2.0
- pip install six
- pip install -r requirements.dev.txt
services: postgresql
before_script:
- createuser pari
- psql -c 'create database  test_pari;' -U postgres
- psql -d test_pari -c "CREATE EXTENSION postgis;"
script: python manage.py test author --keepdb
deploy:
  provider: script
  script: sh deploy.sh
  skip_cleanup: true
  on:
    branch: master
addons:
  ssh_known_hosts:
  - ec2-13-58-83-216.us-east-2.compute.amazonaws.com
