language: python

python:
  - "2.7"

install:
        - "pip install ansible==2.0"
        - "pip install six"
        - "pip install -r requirements.dev.txt"

services:
     postgresql

before_script:
       - createuser pari
       - psql -c 'create database  test_pari;' -U postgres
       - psql -d test_pari -c "CREATE EXTENSION postgis;"

script: python manage.py test author --keepdb
