language: python
python:
  - "2.7"
  # command to install dependencies
  #todo add a secret passpharse for enc
before_install:
   openssl aes-256-cbc -K $encrypted_cbd4cd1910df_key -iv $encrypted_cbd4cd1910df_iv -in pari-test.pem.enc -out pari-test.pem -d

install:
        - "pip install six"
        - "pip install -r requirements.dev.txt"

#Starting services
services:
     postgresql
before_script:
       - createuser pari
       - psql -c 'create database pari;' -U postgres
       - psql -c 'create database  test_pari;' -U postgres
       - psql -d pari -c "CREATE EXTENSION postgis;"
       - psql -d test_pari -c "CREATE EXTENSION postgis;"


# command to run tests
#todo Make all tests to run once functional tests is done
script: python manage.py test author --keepdb

deploy:
   provider: script
   script: sh deploy.sh
   skip_cleanup: true

addons:
   ssh_known_hosts:
   - ec2-52-14-252-14.us-east-2.compute.amazonaws.com


 
