language: python
python:
  - "2.7"
  # command to install dependencies
install:
        - "pip install six"
        - "pip install -r requirements.txt"

#Starting services
services:
     postgresql
before_script:
       - psql -c 'create database pari;' -U pari
       - psql -c 'create database test_pari;' -U pari


# command to run tests
script: python manage.py test