language: python
python:
  - "2.7"
  # command to install dependencies
install:
        - "pip install six"
        - "pip install -r requirements.dev.txt"

#Starting services
services:
     postgresql
before_script:
       - createuser pari
       - psql -c 'create database pari;' -U postgres
       - psql -c 'create database  test_pari;' -U postgres
       - psql -d pari -c "CREATE EXTENSION postgis;"
       - psql -d test_pari -c "CREATE EXTENSION postgis;"


# command to run tests
script: python manage.py test author --keepdb
